# Generated by Django 5.0.1 on 2024-07-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0004_alter_primcont_emails_alter_primcont_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primcont',
            name='emails',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
