# Generated by Django 5.0.1 on 2024-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0005_alter_primcont_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primcont',
            name='link_precedence',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20),
        ),
    ]
