# Generated by Django 5.0.1 on 2024-07-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0007_alter_primcont_phones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecCont',
        ),
    ]
